# Generated by Django 6.0.1 on 2026-01-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_passwordresettoken_alter_customer_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.FileField(
                blank=True, null=True, upload_to="customer_profiles/"
            ),
        ),
    ]
