# Generated by Django 6.0.1 on 2026-01-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_passwordresettoken_alter_customer_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
