# Generated by Django 6.0.2 on 2026-02-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="plan_tier",
            field=models.IntegerField(default=1),
        ),
    ]
