# Generated by Django 6.0.1 on 2026-01-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_passwordresettoken_alter_customer_password_and_more"),
        ("product_buy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbuy",
            name="buyerName",
        ),
        migrations.AlterField(
            model_name="productbuy",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_posts",
                to="customer.customer",
            ),
            preserve_default=False,
        ),
    ]
