# Generated by Django 6.0.2 on 2026-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_sell", "0002_remove_productsell_phoneno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsell",
            name="unit",
            field=models.CharField(
                choices=[("kg", "Kg"), ("ton", "Ton")], default="kg", max_length=10
            ),
        ),
    ]
