# Generated by Django 6.0.2 on 2026-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_sell", "0003_productsell_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsell",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms (kg)"),
                    ("ton", "Metric Tons"),
                    ("quintal", "Quintals"),
                    ("g", "Grams"),
                    ("lb", "Pounds"),
                    ("l", "Litres"),
                    ("ml", "Millilitres"),
                    ("box", "Boxes"),
                    ("crate", "Crates"),
                    ("dozen", "Dozens"),
                    ("piece", "Pieces/Numbers"),
                    ("barrel", "Barrels"),
                    ("bag", "Bags/Sacks"),
                    ("bunch", "Bunches"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
