# Generated by Django 6.0.2 on 2026-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_bid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbid",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("INVALID", "Invalid"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
